unlock_door:
  target:
    entity:
      integration: hikvision_intercom
      domain: lock
  fields:
    lock:
      required: true
      default: 1
      selector:
        select:
          options:
            - "1"
