import { defineConfig } from "@playwright/test";
const port = Number(process.env.WISKEY_TEST_PORT || 8765);
export default defineConfig({
  testDir: "./tests",
  testMatch: [
    "station-onboarding.spec.ts",
    "station-lifecycle-review.spec.ts",
    "job-approval.spec.ts",
    "quality-metrics.spec.ts",
    "overview-summary.spec.ts",
    "embed.spec.ts",
    "platform-center.spec.ts",
    "maintenance-queue.spec.ts",
    "accent.spec.ts",
    "priority-workflows.spec.ts",
    "operational.spec.ts",
    "access-design.spec.ts",
    "temporary-renewal.spec.ts",
    "temporary-cancellation.spec.ts",
    "guest-templates.spec.ts",
    "visit-requests.spec.ts",
    "fleet-alerts.spec.ts",
    "investigations.spec.ts",
    "audio-output-cross.spec.ts",
    "operator-scopes.spec.ts",
    "conditional-profiles.spec.ts",
    "data-quality.spec.ts",
    "photo-file.spec.ts",
    "access-scenario.spec.ts",
    "permission-reviews.spec.ts",
    "policy-versions.spec.ts",
    "bulk-renewal.spec.ts",
    "group-suggestions.spec.ts",
    "access-comparison.spec.ts",
  ],
  fullyParallel: true,
  workers: 2,
  use: { baseURL: `http://127.0.0.1:${port}`, headless: true },
  projects: [
    { name: "firefox", use: { browserName: "firefox" } },
    { name: "webkit", use: { browserName: "webkit" } },
  ],
  webServer: {
    command: "node tests/serve.mjs",
    url: `http://127.0.0.1:${port}`,
    reuseExistingServer: !process.env.CI,
  },
  reporter: "list",
});
