name: Hassfest
on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:
permissions:
  contents: read
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: home-assistant/actions/hassfest@master
